[package]
name = "timer_future"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
futures = "0.3.30"
libc = "0.2.158"
log = "0.4.22"
nix = { version = "0.29.0", features = ["socket"] }
tokio = "1.39.2"

[lib]
name = "timer_future"
path = "src/lib.rs"
